// <auto-generated />
using Contacts.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contacts.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220815063338_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Contacts.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UUID"), 1L, 1);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            UUID = 1,
                            Company = "Test",
                            Lastname = "Ecevit",
                            Name = "Sadettin"
                        },
                        new
                        {
                            UUID = 2,
                            Company = "Test",
                            Lastname = "Aksu",
                            Name = "Sezen"
                        },
                        new
                        {
                            UUID = 3,
                            Company = "Test",
                            Lastname = "Senar",
                            Name = "Müzeyyen"
                        });
                });

            modelBuilder.Entity("Contacts.Domain.Entities.ContactInfo", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UUID"), 1L, 1);

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfoTypeId")
                        .HasColumnType("int");

                    b.HasKey("UUID");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            UUID = 1,
                            ContactId = 1,
                            Info = "05xx xxx xx xx",
                            InfoTypeId = 1
                        },
                        new
                        {
                            UUID = 2,
                            ContactId = 1,
                            Info = "Amsterdam",
                            InfoTypeId = 3
                        },
                        new
                        {
                            UUID = 3,
                            ContactId = 2,
                            Info = "05xx xxx xx xx",
                            InfoTypeId = 1
                        },
                        new
                        {
                            UUID = 4,
                            ContactId = 3,
                            Info = "Amsterdam",
                            InfoTypeId = 3
                        },
                        new
                        {
                            UUID = 5,
                            ContactId = 3,
                            Info = "05xx xxx xx xx",
                            InfoTypeId = 3
                        });
                });

            modelBuilder.Entity("Contacts.Domain.Entities.InfoType", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UUID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.ToTable("InfoTypes");

                    b.HasData(
                        new
                        {
                            UUID = 1,
                            Name = "Telefon Numarası"
                        },
                        new
                        {
                            UUID = 2,
                            Name = "E-mail Adresi"
                        },
                        new
                        {
                            UUID = 3,
                            Name = "Konum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
